backend:
  name: 'github'
  repo: 'JoeNg93/vtqh-blog'
  branch: 'master'

slug:
  clean_accents: true # Clean accents (e.g. dau Tieng Viet) when generating slugs

media_folder: 'static/assets'
public_folder: '/assets'

publish_mode: 'editorial_workflow'

collections:
  - label: 'Posts'
    name: 'post'
    folder: 'content/post'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '[{{year}}-{{month}}-{{day}}] {{title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Sub Title',
          name: 'subtitle',
          widget: 'string',
          required: false,
        }
      - { label: 'Author', name: 'author', widget: 'hidden', default: 'Hunn' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - {
          label: 'Categories',
          name: 'categories',
          widget: 'list',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    sortable_fields: ['date', 'title']
    view_groups:
      - { label: 'Year', field: 'date', pattern: '\d{4}' }
